### PR TITLE
MatTable Table Filter, get data from API

### PR DESCRIPTION
**Pull request by enkodellc**
Used code from #59 from @arivera12 to add Filtering and Pulling the table data from an API url. 
Still need to review / test the paging from the APIurl as well as sorting. He did not supply examples so I was testing and integrating with MatTable code. 

The main issue I saw from the paging is that it was focused on querystring parameters for the API variables for paging / sorting from the API server. I want to discuss this with others. The example API I was using was REST and their paging / pagesize parameters where done in the APIurl path not querystring parameters.

### CODE REVIEW

**Comment by arivera12** [comment]
@enkodellc The grid component had a search filter input which works inside the context of the gridview. But if you want to separate them as it should be then you need to add an extra parameter and pass out the filter from the input. For sorting purpose that job is not done yet. For sorting I think we would need some events on the headers for this. But paging works both sides client and server. How to use client paging? if you you pass data to the gridview and/or don't set the apiurl then he will manage paging client side without doing any request. If apiurl is set and no data then it will try to manage paging by requesting the server and passing some parameters as querystring. The querystring props names can be changed if you want to user other names or integrate with existing api.

**Comment by enkodellc** [comment]
Thanks @arivera12  for the explanation. I think after looking at it I had gotten that same impression. I just want to discuss the server side paging with @SamProf, on if that is the most appropriate solution. It could be, but to be safe and to discuss it a bit. Thanks again for submitting the code!

I agree on the sorting requiring it at the head level. I am not sure when I will take a look at that. For my own purpose I need a grouping feature first so that is the path I will take.

**Comment by arivera12** [comment]
Remember that paging on server side should be done on sql not in the component itself. If you using entity framework you should do some .Skip().Take() before returning results.

**Comment by enkodellc** [comment]
Thanks, I was just overthinking a bit on how the APIurl parameters might need to be customized. I have not done a lot of REST.  Looks like your solution will be great for rest:  

https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9  
Section 6) Searching, sorting, filtering and pagination

Most of your code is in this PR but I will need to test and add the summary data with examples. When I see a repo I love seeing examples and the documentation and I really appreciate how @SamProf setup the BlazorFiddle for MatBlazor! Great for beginners like me.

**Comment by arivera12** [comment]
If you need any help trying to achieve something let me know I can give you recomendations. I don't have too much free time I work the seven days of the week. I can help you if you are stuck somewhere in the code. I was planning to support sorting (making a <BlazorTh> sub components which holds the column name that wants to be sorted and state of sorting ascending/descending) and column reorders (using Dragula) but blazor now supports drag and drop events but this kind of features customers are so noob that doesn't even use them at all. I am an old developer I have 9  years developing enterprise and government apps.

**Pull request merged**
